name: creatego

packages:
  - packages
  - packages/packages/*
  - backend/backend_client
  - backend/backend_server
  - backend/supabase
  - ide
  - ide/*
  - starter_app

scripts:
  analyze:
    exec: dart analyze .